version: 1.0.{build}

image: Visual Studio 2017

environment:
  matrix:
    - CMAKE_GENERATOR: "Visual Studio 15 2017"
    - CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"

build:
  verbosity: minimal

before_build:
- git submodule update --init --recursive --checkout
- cmake -H. -Bbuild -G "%CMAKE_GENERATOR%"

build_script:
- cmake --build build
- ctest -V
